import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex h-[70px] justify-between bg-black px-4 py-4 ">
          <Image
            src={"vector.svg"}
            height={25}
            width={25}
            alt={"Vita Libratum Logo"}
          />
          <Image
            src={"LOGO.svg"}
            height={30}
            width={45}
            alt={"Vita Libratum Logo"}
          />
          <Button />
        </div>
        <div className="relative flex flex-col gap-3 overflow-hidden bg-primary-200 p-6 ">
          <h1 className="text-center text-[20px] text-white">Lorem Ipsum</h1>
          <div className="text-center text-[25px] font-medium text-white">
            <p>Lorem ipsum </p>
            <p>
              dolor sit amet, consectetur adipisicing elit. Eum, doloremque?
            </p>
          </div>

          <Image
            className="self-center"
            src={"/cellphones.png"}
            width={230}
            height={1258}
            alt={"Vita Libratum Logo"}
          />

          <Button2 />
          <div className="absolute top-[-50px] right-[-200px] h-full w-full">
            <Image src={"/last.png"} fill alt={"Vita Libratum Logo"} />
          </div>
          <Image src={"/past.png"} fill alt={"Vita Libratum Logo"} />
          <div className="absolute bottom-[-10px] left-0 h-24 w-screen">
            <Image src={"waves2.svg"} fill alt={"Vita Libratum Logo"} />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

// <Link href="/api/auth/login">Login</Link>
// <Link href="/api/auth/logout">LogOut</Link>

const Button = () => {
  const router = useRouter();
  return (
    <button
      className=" font-sm flex h-[22px] w-[86px] justify-center gap-2 self-center rounded-md bg-primary-300 align-middle  text-primary_text"
      onClick={() => {
        void router.push("/api/auth/login");
      }}
    >
      <p className="self-center text-[10px] font-bold">Sou Aluno</p>
      <Image
        className="self-center"
        src={"but_icon.svg"}
        height={10}
        width={10}
        alt={"Vita Libratum Logo"}
      />
    </button>
  );
};

const Button2 = () => {
  const router = useRouter();
  return (
    <button
      className=" font-sm mb-20 flex h-[46px] w-[205px] justify-center gap-2 self-center rounded-md bg-white p-[12px]  align-middle text-primary-300 "
      onClick={() => {
        void router.push("/api/auth/login");
      }}
    >
      <p className="self-center text-[15px] font-bold">Entrar para o time</p>
      <Image
        className="self-center "
        src={"but_icon2.svg"}
        height={15}
        width={15}
        alt={"Vita Libratum Logo"}
      />
    </button>
  );
};
