import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useUser } from "@auth0/nextjs-auth0/client";
import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { user, error, isLoading } = useUser();

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Link href="/api/auth/login">Login</Link>

        {user && (
          <div>
            <img src={user.picture || ""} alt={user.name || ""} />
            <p>{user.sid}</p>
            <h2>{user.name}</h2>
            <p>{user.email}</p>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
