import { type NextPage } from "next";
import Head from "next/head";
import { LandinPage } from "../containers/LP";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandinPage />
    </>
  );
};

export default Home;
